server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: wc18329261252
  redis:
    host: localhost
    port: 6379
    database: 2
    jedis:
      pool:
        max-wait: 1000ms
        max-active: 100
        max-idle: 100
        min-idle: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
#    template-loader-path: classpath:/templates
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: false
#    expose-session-attributes: false
#    request-context-attribute: req
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**
#  web:
#    resources:
#        static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        #定义消费者最多同时处理10个消息
        prefetch: 10
        #消息手动确认
        acknowledge-mode: manual
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true